package tackleset;

import static tackleset.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INSTIKI
 */
public class ftackleset extends javax.swing.JFrame {
    DefaultTableModel dTKS  = new DefaultTableModel();
    /**
     * Creates new form fMahasiswa
     */
    public ftackleset() throws SQLException {
        initComponents();
        tTKS.setModel(dTKS);
        dTKS.addColumn("Nomor");
        dTKS.addColumn("ROD");
        dTKS.addColumn("REEL");
        dTKS.addColumn("PRICE");
        
        lsDtTKS();
        fieldEnabled(false);
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
        
    }
    private void fieldEnabled(boolean opsi){
        txNO.setEditable(opsi);
        txROD.setEditable(opsi);
        txREEL.setEditable(opsi);
        txPRICE.setEditable(opsi);
    }
     private void tombol(boolean opsi){
        cBaru.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    private void clearForm(){
        txNO.setText("");
        txROD.setText("");
        txREEL.setText("");
        txPRICE.setText("");
    }
        
       private void lsDtTKS() throws SQLException{
           Connection cnn = koneksi();
           
           dTKS.getDataVector().removeAllElements();
           dTKS.fireTableDataChanged();
           
           if ( !cnn.isClosed()){
               PreparedStatement ps = cnn.prepareStatement("SELECT * FROM tks;");
               ResultSet rs = ps.executeQuery();
               while(rs.next()){
                   Object[] dta = new Object[4];
                        dta[0] = rs.getString("No");
                        dta[1] = rs.getString("Rod");
                        dta[2] = rs.getString("Reel");
                        dta[3] = rs.getString("Price");
                        
                        
                dTKS.addRow(dta);
               }
               cnn.close();
           }
    }
       private void storeData() throws SQLException{
            Connection cnn = koneksi();
            if (!cnn.isClosed()){
                PreparedStatement ps = cnn.prepareStatement("INSERT INTO tks (No,Rod,Reel,Price) VALUES(?,?,?,?)");
                ps.setString(1, txNO.getText());
                ps.setString(2, txROD.getText());
                ps.setString(3, txREEL.getText());
                ps.setString(4, txPRICE.getText());
                ps.executeUpdate();
                cnn.close();
            }
       }
       private void updateData() throws SQLException{
            Connection cnn = koneksi();
            if (!cnn.isClosed()){
                PreparedStatement ps = cnn.prepareStatement("UPDATE tks SET Rod=?,Reel=?,Price=? WHERE No=?;");
                ps.setString(4, txNO.getText());
                ps.setString(1, txROD.getText());
                ps.setString(2, txREEL.getText());
                ps.setString(3, txPRICE.getText());
                ps.executeUpdate();
                cnn.close();
            }
       }
       
       private void destoryData() throws SQLException{
           Connection cnn = koneksi();
            if (!cnn.isClosed()){
                PreparedStatement ps = cnn.prepareStatement("DELETE FROM tks WHERE No=?;");
                ps.setString(1, txNO.getText());
                ps.executeUpdate();
                cnn.close();
            }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNO = new javax.swing.JTextField();
        txROD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txREEL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txPRICE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTKS = new javax.swing.JTable();
        cUbah = new javax.swing.JButton();
        cBaru = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setText("Fishing Set");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel2.setText("No:");

        txNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNOActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel3.setText("Rod :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel4.setText("Reel :");

        txREEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txREELActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel5.setText("Price :");

        tTKS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTKS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTKSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTKS);

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBaru)
                        .addGap(18, 18, 18)
                        .addComponent(cUbah)
                        .addGap(18, 18, 18)
                        .addComponent(cHapus)
                        .addGap(18, 18, 18)
                        .addComponent(cTutup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addComponent(txROD, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(txPRICE)
                    .addComponent(txREEL)
                    .addComponent(txNO))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txREEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru)
                            .addComponent(cUbah)
                            .addComponent(cTutup)
                            .addComponent(cHapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNOActionPerformed

    private void txREELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txREELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txREELActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        int jwb = JOptionPane.showOptionDialog(this, "yakin nihhh hapus data" +txNO.getText()+"?", "konfirmasi hapus data",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jwb == JOptionPane.YES_OPTION){
        try {
            destoryData();
            lsDtTKS();
            clearForm();
            cUbah.setEnabled(false);
            cHapus.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(ftackleset.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_cHapusActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        int opsi = JOptionPane.showOptionDialog(this,"Anda yakin menutup form?","Konfirmasi tutup form",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null,null);
        if(opsi == JOptionPane.YES_OPTION){        
            System.exit(0);
        }
    }//GEN-LAST:event_cTutupActionPerformed

    private void tTKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTKSMouseClicked
        txNO.setText(tTKS.getValueAt(tTKS.getSelectedRow(), 0).toString());
        txROD.setText(tTKS.getValueAt(tTKS.getSelectedRow(), 1).toString());
        String prc = (tTKS.getValueAt(tTKS.getSelectedRow(), 3).toString().equals("1jt"))?"1.000.000":"2.000.000";
        txPRICE.setText (prc);
        txREEL.setText(tTKS.getValueAt(tTKS.getSelectedRow(), 2).toString());
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
    }//GEN-LAST:event_tTKSMouseClicked

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
        if(cBaru.getText().equals("Baru")){
            cBaru.setText("Simpan");
            cTutup.setText("Batal");
            cUbah.setEnabled(false);
            cHapus.setEnabled(false);
            clearForm();
            fieldEnabled(true);
        }else{
            if(!txNO.getText().equals("")){
                try {
                    storeData();
                    lsDtTKS();
                } catch (SQLException ex) {
                    Logger.getLogger(ftackleset.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            cBaru.setText("Baru");
            cTutup.setText("Tutup");
            clearForm();
            fieldEnabled(false);
        }
    }//GEN-LAST:event_cBaruActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        if(cUbah.getText().equals("Ubah")){
            cUbah.setText("Simpan");
            cTutup.setText("Batal");
            cBaru.setEnabled(false);
            cHapus.setEnabled(false);

            fieldEnabled(true);
            txNO.setEditable(false);
        }else{
            if(!txNO.getText().equals("")){
                try {
                    storeData();
                    lsDtTKS();
                } catch (SQLException ex) {
                    Logger.getLogger(ftackleset.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            cUbah.setText("Simpan");
            cTutup.setText("Tutup");
            clearForm();
            fieldEnabled(false);
        }
    }//GEN-LAST:event_cUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ftackleset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ftackleset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ftackleset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ftackleset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ftackleset().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ftackleset.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTKS;
    private javax.swing.JTextField txNO;
    private javax.swing.JTextField txPRICE;
    private javax.swing.JTextField txREEL;
    private javax.swing.JTextField txROD;
    // End of variables declaration//GEN-END:variables
}
